import 'dart:convert';
import 'dart:async';
import 'dart:ui' as ui;
import 'package:http/http.dart' as http;
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:flutter_map_marker_cluster/flutter_map_marker_cluster.dart';
import 'package:latlong2/latlong.dart';
import 'package:geolocator/geolocator.dart';
import 'package:url_launcher/url_launcher.dart';

import 'taxi_spots.dart';
import 'berlin_places.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: const FirebaseOptions(
      apiKey: 'AIzaSyDryCyRT5biLr1EF9q2hYxJi-jRD380YW4',
      authDomain: 'taxispot-berlin.firebaseapp.com',
      projectId: 'taxispot-berlin',
      storageBucket: 'taxispot-berlin.firebasestorage.app',
      messagingSenderId: '331677000836',
      appId: '1:331677000836:web:9218311a71134d8fdf0ed1',
      measurementId: 'G-GB9KGZZ7DD',
    ),
  );
  // Sign in anonymously when the app starts.
try {
  if (FirebaseAuth.instance.currentUser == null) {
    await FirebaseAuth.instance.signInAnonymously();
  }
  debugPrint('Anonymous authentication successful');
} catch (e) {
  debugPrint('Anonymous authentication failed: $e');
}

  // Analytics collection is enabled in this build.
  await FirebaseAnalytics.instance.setAnalyticsCollectionEnabled(true);

  runApp(const TaxiSpotApp());
}

class TaxiSpot {
  final String name;
  final LatLng point;
  final int? score;
  final String note;

  const TaxiSpot(
    this.name,
    this.point,
    this.score,
    this.note,
  );
}

// These five locations and their scores are examples, not live demand data.
const spots = <TaxiSpot>[
  TaxiSpot(
    'Berlin Hauptbahnhof',
    LatLng(52.5251, 13.3694),
    92,
    'Hauptbahnhof • Beispielbewertung',
  ),
  TaxiSpot(
    'Alexanderplatz',
    LatLng(52.5219, 13.4132),
    84,
    'Tourismus • Beispielbewertung',
  ),
  TaxiSpot(
    'Zoologischer Garten',
    LatLng(52.5073, 13.3326),
    78,
    'Bahnhof • Beispielbewertung',
  ),
  TaxiSpot(
    'Potsdamer Platz',
    LatLng(52.5096, 13.3760),
    73,
    'Hotels • Beispielbewertung',
  ),
  TaxiSpot(
    'BER Airport',
    LatLng(52.3667, 13.5033),
    88,
    'Flughafen • Beispielbewertung',
  ),
];


// Event data is generated by GitHub Actions in web/events.json.
class BerlinEvent {
  final String name;
  final String date;
  final String time;
  final String venue;
  final String url;
  final LatLng location;

  const BerlinEvent({required this.name, required this.date,
    required this.time, required this.venue, required this.url,
    required this.location});

  static BerlinEvent? fromJson(Map<String, dynamic> json) {
    final latitude = num.tryParse(json['latitude'].toString());
    final longitude = num.tryParse(json['longitude'].toString());
    
    if (latitude is! num ||
    longitude is! num ||
    latitude < -90 ||
    latitude > 90 ||
    longitude < -180 ||
    longitude > 180) {
  return null;
}
    final name = json['name'];
    if (name is! String || name.trim().isEmpty) return null;
    return BerlinEvent(
      name: name,
      date: json['date'] is String ? json['date'] as String : '',
      time: json['time'] is String ? json['time'] as String : '',
      venue: json['venue'] is String && (json['venue'] as String).trim().isNotEmpty
          ? json['venue'] as String : 'Veranstaltungsort unbekannt',
      url: json['url'] is String ? json['url'] as String : '',
      location: LatLng(latitude.toDouble(), longitude.toDouble()),
    );
  }
}

class TaxiSpotApp extends StatelessWidget {
  const TaxiSpotApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'TaxiSpot Berlin',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.amber,
        ),
        useMaterial3: true,
      ),
      home: const MapScreen(),
    );
  }
}

class MapScreen extends StatefulWidget {
  const MapScreen({super.key});

  @override
  State<MapScreen> createState() => _MapScreenState();
}

class _MapScreenState extends State<MapScreen> {
  final MapController _mapController = MapController();

  LatLng? _driver;
  TaxiSpot? _selected = spots.first;
  BerlinPlace? _selectedPlace;
  BerlinEvent? _selectedEvent;
  List<BerlinEvent> _events = [];
  String _eventFilter = 'all'; // all, today, tomorrow
  bool _eventsLoading = true;
  String? _eventsError;
  bool _showEvents = true;
  List<BerlinPlace> _places = [];
  bool _placesLoading = true;
  String? _placesError;
  bool _showPlaces = true;
  bool _showTaxiStands = true;
  int _demandFilter = 0; // 0: all, 1: 90-100, 2: 80-89, 3: 60-79

  List<TaxiSpot> _allSpots = List.of(spots);

  bool _loading = true;
  String? _loadError;
  double? _temperature;
  double? _precipitation;
  String? _berlinTime;
  String? _weatherError;
  bool _weatherLoading = true;
  Timer? _refreshTimer;
  int _refreshTicks = 0;
  late DateTime _lastDemandRefresh;

  int? _uniqueVisitors;
  String? _counterError;
  StreamSubscription<DocumentSnapshot<Map<String, dynamic>>>? _counterSubscription;

  Future<void> _startCounters() async {
    try {
      final auth = FirebaseAuth.instance;
      final user = auth.currentUser ?? (await auth.signInAnonymously()).user;
      if (user == null) throw StateError('Anonymous sign-in failed');

      final db = FirebaseFirestore.instance;
      final stats = db.collection('public_stats').doc('global');
      final visitor = db.collection('visitors').doc(user.uid);
      // A single atomic transaction records one app launch and, for a new
      // anonymous account, one unique visitor. This counts installations/accounts,
      // not provably unique humans; clearing browser storage creates a new ID.
      await db.runTransaction((transaction) async {
        final previous = await transaction.get(visitor);
        transaction.set(visitor, {
          if (!previous.exists) 'createdAt': FieldValue.serverTimestamp(),
          'lastOpenedAt': FieldValue.serverTimestamp(),
        }, SetOptions(merge: true));
        transaction.set(stats, {
          'visits': FieldValue.increment(1),
          if (!previous.exists) 'uniqueVisitors': FieldValue.increment(1),
          'updatedAt': FieldValue.serverTimestamp(),
        }, SetOptions(merge: true));
      });

      _counterSubscription = stats.snapshots().listen((snapshot) {
        if (!mounted) return;
        final data = snapshot.data();
        setState(() {
          _uniqueVisitors = (data?['uniqueVisitors'] as num?)?.toInt();
          _counterError = null;
        });
      }, onError: (Object error) {
        debugPrint('Counter stream error: $error');
        if (mounted) setState(() => _counterError = 'Statistik nicht verfügbar');
      });
    } catch (error) {
      debugPrint('Counter setup error: $error');
      if (mounted) setState(() => _counterError = 'Statistik nicht verfügbar');
    }
  }

  Future<void> _recordPlaceView() async {
    try {
      await FirebaseFirestore.instance.collection('public_stats').doc('global').set({
        'placeViews': FieldValue.increment(1),
        'updatedAt': FieldValue.serverTimestamp(),
      }, SetOptions(merge: true));
    } catch (error) {
      debugPrint('Place view count error: $error');
    }
  }

  Widget _counterBanner() {
    final text = _counterError ??
        'Besucher: ${_uniqueVisitors?.toString() ?? "…"}';
    return Text(
      text,
      style: const TextStyle(fontSize: 11),
      maxLines: 1,
      overflow: TextOverflow.ellipsis,
    );
  }


  // Berlin local time, including European daylight saving time.
  DateTime _berlinNow() {
    final utc = DateTime.now().toUtc();
    DateTime lastSunday(int month) {
      final last = DateTime.utc(utc.year, month + 1, 0);
      return DateTime.utc(utc.year, month, last.day - last.weekday % 7, 1);
    }
    final summer = !utc.isBefore(lastSunday(3)) && utc.isBefore(lastSunday(10));
    return utc.add(Duration(hours: summer ? 2 : 1));
  }

  // Experimental 0–100 index, NOT a probability or observed passenger demand.
  // No event bonus is awarded without a verified event schedule.
  int _demandIndex(BerlinPlaceType type) {
    final now = _berlinNow();
    final hour = now.hour;
    final weekend = now.weekday >= 6;
    int base;
    int time;
    switch (type) {
      case BerlinPlaceType.hotel:
        base = 40;
        time = hour >= 6 && hour < 11 ? 42 : hour >= 17 && hour < 22 ? 25 : 7;
        break;
      case BerlinPlaceType.event:
        base = 30;
        time = hour >= 20 || hour < 2 ? 48 : hour >= 16 ? 20 : 5;
        break;
      case BerlinPlaceType.theatre:
        base = 30;
        time = hour >= 21 || hour < 1 ? 48 : hour >= 17 ? 20 : 4;
        break;
      case BerlinPlaceType.conference:
        base = 35;
        time = !weekend && hour >= 16 && hour < 20 ? 45 :
            !weekend && hour >= 8 && hour < 11 ? 25 : 4;
        break;
    }
    final weather = _precipitation == null ? 0 :
        _precipitation! >= 2 ? 15 : _precipitation! > 0 ? 9 : 0;
    final cold = _temperature != null && _temperature! < 3 ? 4 : 0;
    return (base + time + weather + cold).clamp(0, 100).toInt();
  }

  @override
  void dispose() {
    _counterSubscription?.cancel();
    _refreshTimer?.cancel();
    _mapController.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    _lastDemandRefresh = _berlinNow();
    _startCounters();
    _loadAllSpots();
    _loadPlaces();
    _loadEvents();
    _loadWeather();
    _refreshTimer = Timer.periodic(const Duration(minutes: 5), (_) {
      if (!mounted) return;
      setState(() {
        _lastDemandRefresh = _berlinNow(); // Recalculate using current time.
      });
      _refreshTicks++;
      if (_refreshTicks % 3 == 0) _loadWeather();
    });
  }

  Future<void> _loadEvents() async {
    try {
      // Relative to the deployed GitHub Pages application directory.
      final uri = Uri.base.resolve('events.json');
      final response = await http.get(uri).timeout(const Duration(seconds: 15));
      if (response.statusCode != 200) {
        throw Exception('Events HTTP ${response.statusCode}');
      }
      final decoded = jsonDecode(response.body) as Map<String, dynamic>;
      final raw = decoded['events'];
      if (raw is! List) throw const FormatException('Invalid events list');
      final events = raw.whereType<Map<String, dynamic>>()
          .map(BerlinEvent.fromJson).whereType<BerlinEvent>().toList();
      debugPrint('EVENTS CHECK: JSON=${raw.length}, VALID=${events.length}');
      if (!mounted) return;
      setState(() {
        _events = events;
        _eventsLoading = false;
        _eventsError = null;
      });
    } catch (error) {
      debugPrint('Events load error: $error');
      if (!mounted) return;
      setState(() {
        _eventsLoading = false;
        _eventsError = 'Veranstaltungen konnten nicht geladen werden';
      });
    }
  }

    List<Marker> _buildEventMarkers() {
  final now = _berlinNow();
  final today = DateTime(now.year, now.month, now.day);

  final filteredEvents = _events.where((event) {
    if (_eventFilter == 'all') {
      return true;
    }

    final eventDate = DateTime.tryParse(event.date);
    if (eventDate == null) {
      return false;
    }

    final targetDate = _eventFilter == 'today'
        ? today
        : today.add(const Duration(days: 1));

    return eventDate.year == targetDate.year &&
        eventDate.month == targetDate.month &&
        eventDate.day == targetDate.day;
  });

  return filteredEvents.map((event) => Marker(
    point: event.location,
    width: 44,
    height: 44,
    child: GestureDetector(
      onTap: () => setState(() {
        _selectedEvent = event;
        _selectedPlace = null;
        _selected = null;
      }),
      child: Container(
        decoration: BoxDecoration(
          color: Colors.green.shade700,
          shape: BoxShape.circle,
          border: Border.all(
            color: Colors.white,
            width: 2,
          ),
          boxShadow: const [
            BoxShadow(
              blurRadius: 4,
              color: Colors.black26,
            ),
          ],
        ),
        child: const Icon(
          Icons.event,
          color: Colors.white,
        ),
      ),
    ),
  )).toList();
}

  Future<void> _openEventUrl(String url) async {
    final uri = Uri.tryParse(url);
    if (uri == null || uri.scheme != 'https') {
      _showMessage('Veranstaltungslink nicht verfügbar');
      return;
    }
    try {
      if (!await launchUrl(uri, mode: LaunchMode.externalApplication)) {
        _showMessage('Veranstaltungslink konnte nicht geöffnet werden');
      }
    } catch (error) {
      debugPrint('Event URL error: $error');
      _showMessage('Veranstaltungslink konnte nicht geöffnet werden');
    }
  }

  Future<void> _loadPlaces() async {
    try {
      final places = await BerlinPlacesLoader.load();
      if (!mounted) return;
      setState(() {
        _places = places;
        _placesLoading = false;
        _placesError = null;
      });
    } catch (e) {
      debugPrint('Error loading Berlin places: $e');
      if (!mounted) return;
      setState(() {
        _placesLoading = false;
        _placesError = 'Orte konnten nicht geladen werden';
      });
    }
  }

  Color _placeColor(BerlinPlaceType type) {
    switch (type) {
      case BerlinPlaceType.hotel:
        return Colors.deepPurple;
      case BerlinPlaceType.event:
        return Colors.deepOrange;
      case BerlinPlaceType.theatre:
        return Colors.pink;
      case BerlinPlaceType.conference:
        return Colors.teal;
    }
  }

  IconData _placeIcon(BerlinPlaceType type) {
    switch (type) {
      case BerlinPlaceType.hotel:
        return Icons.hotel;
      case BerlinPlaceType.event:
        return Icons.celebration;
      case BerlinPlaceType.theatre:
        return Icons.music_note;
      case BerlinPlaceType.conference:
        return Icons.groups;
    }
  }

  String _placeLabel(BerlinPlaceType type) {
    switch (type) {
      case BerlinPlaceType.hotel:
        return 'Hotel / Hostel';
      case BerlinPlaceType.event:
        return 'Veranstaltungsort';
      case BerlinPlaceType.theatre:
        return 'Theater / Musik / Kultur';
      case BerlinPlaceType.conference:
        return 'Konferenzzentrum';
    }
  }

  // Black corner brackets indicate experimental index bands, not probabilities.
  Widget _placeMarker(BerlinPlace place, int score) {
    final veryHigh = score >= 90;
    final high = score >= 80;
    final markerSize = veryHigh ? 76.0 : high ? 64.0 : 40.0;
    final circleSize = veryHigh ? 58.0 : high ? 49.0 : 40.0;
    return SizedBox(
      width: markerSize,
      height: markerSize,
      child: Stack(
        alignment: Alignment.center,
        children: [
          if (high)
            Positioned.fill(
              child: CustomPaint(
                painter: _DemandCornersPainter(
                  strokeWidth: veryHigh ? 5 : 3.5,
                  cornerLength: veryHigh ? 19 : 15,
                ),
              ),
            ),
          Container(
            width: circleSize,
            height: circleSize,
            decoration: BoxDecoration(
              color: _placeColor(place.type),
              shape: BoxShape.circle,
              border: Border.all(color: Colors.white, width: 2),
              boxShadow: const [BoxShadow(blurRadius: 4, color: Colors.black26)],
            ),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(_placeIcon(place.type), color: Colors.white,
                    size: veryHigh ? 24 : high ? 20 : 16),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 3),
                  decoration: BoxDecoration(
                    color: Colors.black87,
                    borderRadius: BorderRadius.circular(7),
                  ),
                  child: Text('$score', style: TextStyle(
                    color: Colors.white,
                    fontSize: veryHigh ? 14 : high ? 12 : 10,
                    fontWeight: FontWeight.bold,
                    height: 1.1,
                  )),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  bool _matchesDemandFilter(BerlinPlace place) {
    final score = _demandIndex(place.type);
    switch (_demandFilter) {
      case 1:
        return score >= 90;
      case 2:
        return score >= 80 && score < 90;
      case 3:
        return score >= 60 && score < 80;
      default:
        return true;
    }
  }

  String _demandFilterLabel() {
    switch (_demandFilter) {
      case 1:
        return '90–100';
      case 2:
        return '80–89';
      case 3:
        return '60–79';
      default:
        return 'Alle Orte';
    }
  }

  List<Marker> _buildPlaceMarkers() {
    return _places.where(_matchesDemandFilter).map((place) {
      final score = _demandIndex(place.type);
      final size = score >= 90 ? 76.0 : score >= 80 ? 64.0 : 40.0;
      return Marker(
        point: place.location,
        width: size,
        height: size,
        child: GestureDetector(
          onTap: () {
            setState(() {
              _selectedPlace = place;
              _selectedEvent = null;
              _selected = null;
            });
            _recordPlaceView();
          },
          child: _placeMarker(place, score),
        ),
      );
    }).toList();
  }

  Future<void> _navigateToPoint(LatLng point) async {
    final uri = Uri.https('www.google.com', '/maps/dir/', {
      'api': '1',
      'destination': '${point.latitude},${point.longitude}',
    });
    try {
      final opened = await launchUrl(uri, mode: LaunchMode.externalApplication);
      if (!opened) _showMessage('Navigation konnte nicht geöffnet werden');
    } catch (e) {
      debugPrint('Navigation error: $e');
      _showMessage('Navigation konnte nicht geöffnet werden');
    }
  }

  Future<void> _loadWeather() async {
    if (mounted) {
      setState(() {
        _weatherLoading = true;
        _weatherError = null;
      });
    }
    try {
      final uri = Uri.https('api.open-meteo.com', '/v1/forecast', {
        'latitude': '52.52',
        'longitude': '13.405',
        'current': 'temperature_2m,precipitation',
        'timezone': 'Europe/Berlin',
      });
      final response = await http.get(uri).timeout(const Duration(seconds: 15));
      if (response.statusCode != 200) {
        throw Exception('Weather HTTP ${response.statusCode}');
      }
      final data = jsonDecode(response.body) as Map<String, dynamic>;
      final current = data['current'] as Map<String, dynamic>;
      final time = DateTime.parse(current['time'] as String);
      if (!mounted) return;
      setState(() {
        _temperature = (current['temperature_2m'] as num).toDouble();
        _precipitation = (current['precipitation'] as num).toDouble();
        _berlinTime = '${time.hour.toString().padLeft(2, '0')}:${time.minute.toString().padLeft(2, '0')}';
        _weatherLoading = false;
      });
    } catch (e) {
      debugPrint('Weather error: $e');
      if (!mounted) return;
      setState(() {
        _weatherLoading = false;
        _weatherError = 'Wetterdaten konnten nicht geladen werden';
      });
    }
  }

  Future<void> _loadAllSpots() async {
    try {
      final imported = await loadTaxiSpots();

      if (!mounted) return;

      final importedSpots = imported.map((spot) {
        return TaxiSpot(
          spot.name,
          spot.point,
          null,
          'Taxistand in OpenStreetMap • Nachfrage unbekannt',
        );
      }).toList();

      setState(() {
        _allSpots = [
          ...importedSpots,
          ...spots,
        ];

        if (_allSpots.isNotEmpty) {
          _selected = _allSpots.first;
        }

        _loading = false;
        _loadError = null;
      });
    } catch (e) {
      debugPrint('Error loading taxi spots: $e');

      if (!mounted) return;

      setState(() {
        _loading = false;
        _loadError = 'Importierte Taxistände konnten nicht geladen werden';
      });
    }
  }

  Future<void> _locateMe() async {
    try {
      final enabled =
          await Geolocator.isLocationServiceEnabled();

      if (!enabled) {
        _showMessage('Bitte aktiviere die Standortdienste (GPS)');
        return;
      }

      var permission = await Geolocator.checkPermission();

      if (permission == LocationPermission.denied) {
        permission = await Geolocator.requestPermission();
      }

      if (permission == LocationPermission.denied ||
          permission == LocationPermission.deniedForever) {
        _showMessage('Standortberechtigung wurde nicht erteilt');
        return;
      }

      final p = await Geolocator.getCurrentPosition();

      if (!mounted) return;

      final point = LatLng(
        p.latitude,
        p.longitude,
      );

      setState(() {
        _driver = point;
      });

      _mapController.move(point, 14);
    } catch (e) {
      debugPrint('Location error: $e');
      _showMessage('Dein Standort konnte nicht ermittelt werden');
    }
  }

  Future<void> _navigate(TaxiSpot spot) async {
    final uri = Uri.parse(
      'https://www.google.com/maps/dir/?api=1'
      '&destination=${spot.point.latitude},${spot.point.longitude}',
    );

    try {
      final opened = await launchUrl(
        uri,
        mode: LaunchMode.externalApplication,
      );

      if (!opened) {
        _showMessage('Navigation konnte nicht geöffnet werden');
      }
    } catch (e) {
      debugPrint('Navigation error: $e');
      _showMessage('Navigation konnte nicht geöffnet werden');
    }
  }

  void _showMessage(String message) {
    if (!mounted) return;

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(message)),
    );
  }

  Color _scoreColor(int? score) {
    if (score == null) return Colors.blue;
    if (score >= 85) return Colors.green;
    if (score >= 70) return Colors.orange;
    return Colors.red;
  }

  List<Marker> _buildTaxiMarkers() {
    return _allSpots.map((spot) {
      return Marker(
        point: spot.point,
        width: 46,
        height: 46,
        child: GestureDetector(
          onTap: () {
            setState(() {
              _selected = spot;
              _selectedEvent = null;
              _selectedPlace = null;
            });
          },
          child: Container(
            decoration: BoxDecoration(
              color: _scoreColor(spot.score),
              shape: BoxShape.circle,
              border: Border.all(
                color: Colors.white,
                width: 2,
              ),
              boxShadow: const [
                BoxShadow(
                  blurRadius: 4,
                  color: Colors.black26,
                ),
              ],
            ),
            alignment: Alignment.center,
            child: spot.score == null
                ? const Icon(
                    Icons.local_taxi,
                    color: Colors.white,
                    size: 23,
                  )
                : Text(
                    '${spot.score}',
                    style: const TextStyle(
                      color: Colors.white,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
          ),
        ),
      );
    }).toList();
  }

  Widget _demandRefreshBanner() {
    final hour = _lastDemandRefresh.hour.toString().padLeft(2, '0');
    final minute = _lastDemandRefresh.minute.toString().padLeft(2, '0');
    return Text(
      'Nachfrage-Index aktualisiert: $hour:$minute Uhr · alle 5 Min. · Schätzung',
      style: const TextStyle(fontSize: 11),
      maxLines: 1,
      overflow: TextOverflow.ellipsis,
    );
  }

  Widget _weatherBanner() {
    if (_weatherLoading) {
      return const Text('Berliner Wetter wird geladen ...');
    }
    if (_weatherError != null) {
      return Text(_weatherError!);
    }
    final rain = _precipitation == null
        ? 'Niederschlag nicht verfügbar'
        : _precipitation! > 0
            ? 'Niederschlag: ${_precipitation!.toStringAsFixed(1)} mm'
            : 'Kein Niederschlag gemeldet';
    return Text(
      'Berlin · Wetterstand ${_berlinTime ?? '--:--'} Uhr  •  '
      '${_temperature?.toStringAsFixed(1) ?? '--'}°C  •  $rain',
      style: const TextStyle(fontSize: 12),
      maxLines: 2,
      overflow: TextOverflow.ellipsis,
    );
  }

  @override
  Widget build(BuildContext context) {
    final demoSpots = _allSpots
        .where((spot) => spot.score != null)
        .toList()
      ..sort(
        (a, b) => b.score!.compareTo(a.score!),
      );

    return Scaffold(
      appBar: AppBar(
        toolbarHeight: 106,
        backgroundColor: Colors.amber,
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'TaxiSpot Berlin',
              style: TextStyle(
                fontWeight: FontWeight.bold,
              ),
            ),
            Text(
              _loading
                  ? 'Taxistände werden geladen ...'
                  : '${_allSpots.length} Taxistände · ${_places.length} Orte · ${_events.length} Events',
              style: const TextStyle(fontSize: 12),
            ),
            _weatherBanner(),
            _demandRefreshBanner(),
            _counterBanner(),
          ],
        ),
      ),
      body: Stack(
        children: [
          FlutterMap(
            mapController: _mapController,
            options: const MapOptions(
              initialCenter: LatLng(52.5200, 13.4050),
              initialZoom: 11.5,
            ),
            children: [
              TileLayer(
                urlTemplate:
                    'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
                userAgentPackageName: 'com.taxispot.berlin',
              ),

              // Group nearby taxi stands into clusters.
              if (_showTaxiStands)
                MarkerClusterLayerWidget(
                options: MarkerClusterLayerOptions(
                  maxClusterRadius: 60,
                  size: const Size(48, 48),
                  markers: _buildTaxiMarkers(),
                  builder: (context, markers) {
                    return Container(
                      decoration: BoxDecoration(
                        color: Colors.amber,
                        shape: BoxShape.circle,
                        border: Border.all(
                          color: Colors.white,
                          width: 3,
                        ),
                        boxShadow: const [
                          BoxShadow(
                            blurRadius: 5,
                            color: Colors.black26,
                          ),
                        ],
                      ),
                      alignment: Alignment.center,
                      child: Text(
                        '${markers.length}',
                        style: const TextStyle(
                          color: Colors.black,
                          fontWeight: FontWeight.bold,
                          fontSize: 15,
                        ),
                      ),
                    );
                  },
                ),
              ),

              // POIs use their own cluster layer and distinct icons.
              if (_showPlaces)
                MarkerClusterLayerWidget(
                  options: MarkerClusterLayerOptions(
                    maxClusterRadius: 55,
                    size: const Size(46, 46),
                    markers: _buildPlaceMarkers(),
                    builder: (context, markers) => Container(
                      alignment: Alignment.center,
                      decoration: BoxDecoration(
                        color: Colors.deepPurple.shade100,
                        shape: BoxShape.circle,
                        border: Border.all(color: Colors.deepPurple, width: 2),
                      ),
                      child: Text(
                        '${markers.length}',
                        style: const TextStyle(fontWeight: FontWeight.bold),
                      ),
                    ),
                  ),
                ),

              // Ticketmaster events, clustered independently from static POIs.
              if (_showEvents)
                MarkerClusterLayerWidget(
                  options: MarkerClusterLayerOptions(
                    maxClusterRadius: 55,
                    size: const Size(46, 46),
                    markers: _buildEventMarkers(),
                    builder: (context, markers) => Container(
                      alignment: Alignment.center,
                      decoration: BoxDecoration(
                        color: Colors.green.shade100,
                        shape: BoxShape.circle,
                        border: Border.all(color: Colors.green.shade800, width: 2),
                      ),
                      child: Text('${markers.length}',
                        style: const TextStyle(fontWeight: FontWeight.bold)),
                    ),
                  ),
                ),

              // Driver location marker is separate from taxi stand clusters.
              if (_driver != null)
                MarkerLayer(
                  markers: [
                    Marker(
                      point: _driver!,
                      width: 48,
                      height: 48,
                      child: const Icon(
                        Icons.my_location,
                        color: Colors.black,
                        size: 40,
                      ),
                    ),
                  ],
                ),
            ],
          ),

          Positioned(
            right: 14,
            top: 14,
            child: FloatingActionButton.small(
              heroTag: 'locate',
              onPressed: _locateMe,
              backgroundColor: Colors.white,
              child: const Icon(Icons.my_location),
            ),
          ),

          Positioned(
            right: 14,
            top: 72,
            child: FloatingActionButton.small(
              heroTag: 'places',
              tooltip: _showPlaces ? 'Orte ausblenden' : 'Orte anzeigen',
              backgroundColor: Colors.white,
              onPressed: () => setState(() {
                _showPlaces = !_showPlaces;
                if (!_showPlaces) _selectedPlace = null;
              }),
              child: Icon(
                _showPlaces ? Icons.layers : Icons.layers_clear,
                color: Colors.deepPurple,
              ),
            ),
          ),
          Positioned(
            right: 14,
            top: 130,
            child: FloatingActionButton.small(
              heroTag: 'taxiVisibility',
              tooltip: _showTaxiStands
                  ? 'Taxistände ausblenden'
                  : 'Taxistände anzeigen',
              backgroundColor: _showTaxiStands ? Colors.white : Colors.black,
              onPressed: () => setState(() {
                _showTaxiStands = !_showTaxiStands;
                if (!_showTaxiStands) _selected = null;
              }),
              child: Icon(
                _showTaxiStands ? Icons.local_taxi : Icons.local_taxi_outlined,
                color: _showTaxiStands ? Colors.blue : Colors.white,
              ),
            ),
          ),
          Positioned(
            right: 14,
            top: 188,
            child: Material(
              color: _demandFilter == 0 ? Colors.white : Colors.black,
              shape: const CircleBorder(),
              elevation: 5,
              child: PopupMenuButton<int>(
                tooltip: 'Nachfrage-Index filtern',
                initialValue: _demandFilter,
                icon: Icon(Icons.filter_alt,
                    color: _demandFilter == 0 ? Colors.black : Colors.white),
                onSelected: (value) => setState(() {
                  _demandFilter = value;
                  if (_selectedPlace != null &&
                      !_matchesDemandFilter(_selectedPlace!)) {
                    _selectedPlace = null;
                  }
                }),
                itemBuilder: (context) => const [
                  PopupMenuItem(value: 0, child: Text('Alle Orte')),
                  PopupMenuItem(value: 1, child: Text('Index 90–100')),
                  PopupMenuItem(value: 2, child: Text('Index 80–89')),
                  PopupMenuItem(value: 3, child: Text('Index 60–79')),
                ],
              ),
            ),
          ),
          Positioned(
            right: 14,
            top: 246,
            child: FloatingActionButton.small(
              heroTag: 'eventsVisibility',
              tooltip: _showEvents ? 'Events ausblenden' : 'Events anzeigen',
              backgroundColor: Colors.white,
              onPressed: () => setState(() {
                _showEvents = !_showEvents;
                if (!_showEvents) _selectedEvent = null;
              }),
              child: Icon(_showEvents ? Icons.event : Icons.event_busy,
                  color: Colors.green.shade800),
            ),
          ),
          if (_eventsLoading)
            const Positioned(left: 14, top: 176,
              child: Chip(label: Text('Events werden geladen ...'))),
          if (_eventsError != null)
            Positioned(left: 14, top: 176,
              child: Chip(label: Text(_eventsError!))),

          if (_demandFilter != 0 && _showPlaces && !_placesLoading)
            Positioned(
              left: 14,
              top: 120,
              child: Chip(
                label: Text('${_demandFilterLabel()}: '
                    '${_places.where(_matchesDemandFilter).length} Orte'),
              ),
            ),
          if (_placesLoading)
            const Positioned(
              left: 14,
              top: 66,
              child: Chip(label: Text('Orte werden geladen ...')),
            ),
          if (_placesError != null)
            Positioned(
              left: 14,
              top: 66,
              child: Chip(label: Text(_placesError!)),
            ),

          if (_loading)
            const Positioned(
              left: 14,
              top: 14,
              child: Chip(
                label: Text('Taxistände werden geladen ...'),
              ),
            ),

          if (_loadError != null)
            Positioned(
              left: 14,
              top: 14,
              child: Chip(
                label: Text(_loadError!),
              ),
            ),

          if (_selectedEvent != null && _showEvents)
            Positioned(
              left: 12, right: 12, bottom: 12,
              child: Card(
                elevation: 8,
                child: Padding(
                  padding: const EdgeInsets.all(14),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      Row(children: [
                        Icon(Icons.event, color: Colors.green.shade800),
                        const SizedBox(width: 8),
                        Expanded(child: Text(_selectedEvent!.name,
                          style: const TextStyle(fontSize: 17,
                            fontWeight: FontWeight.bold))),
                        IconButton(
                          onPressed: () => setState(() => _selectedEvent = null),
                          icon: const Icon(Icons.close)),
                      ]),
                      Text(_selectedEvent!.venue),
                      Text('${_selectedEvent!.date} · ${_selectedEvent!.time}',
                        style: const TextStyle(fontSize: 12)),
                      const SizedBox(height: 8),
                      FilledButton.icon(
                        onPressed: () => _navigateToPoint(_selectedEvent!.location),
                        icon: const Icon(Icons.navigation),
                        label: const Text('Route starten'),
                      ),
                      if (_selectedEvent!.url.isNotEmpty)
                        TextButton.icon(
                          onPressed: () => _openEventUrl(_selectedEvent!.url),
                          icon: const Icon(Icons.open_in_new),
                          label: const Text('Eventdetails öffnen'),
                        ),
                    ],
                  ),
                ),
              ),
            ),

          if (_selectedPlace != null && _showPlaces)
            Positioned(
              left: 12,
              right: 12,
              bottom: 12,
              child: Card(
                elevation: 8,
                child: Padding(
                  padding: const EdgeInsets.all(14),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      Row(
                        children: [
                          Icon(
                            _placeIcon(_selectedPlace!.type),
                            color: _placeColor(_selectedPlace!.type),
                          ),
                          const SizedBox(width: 8),
                          Expanded(
                            child: Text(
                              _selectedPlace!.name,
                              style: const TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                          IconButton(
                            onPressed: () => setState(() => _selectedPlace = null),
                            icon: const Icon(Icons.close),
                          ),
                        ],
                      ),
                      Text(_placeLabel(_selectedPlace!.type)),
                      const Text('Besucherzahl: keine verlässlichen Daten verfügbar',
                          style: TextStyle(fontSize: 12)),
                      const SizedBox(height: 4),
                      Text('Experimenteller Nachfrage-Index: '
                          '${_demandIndex(_selectedPlace!.type)}/100'),
                      const Text(
                        'Heuristische Schätzung nach Ortstyp, Berliner Uhrzeit und Wetter. '
                        'Keine Wahrscheinlichkeit, keine Live-Fahrgastdaten. '
                        'Veranstaltungstermine noch nicht berücksichtigt.',
                        style: TextStyle(fontSize: 12),
                      ),
                      const SizedBox(height: 10),
                      FilledButton.icon(
                        onPressed: () => _navigateToPoint(_selectedPlace!.location),
                        icon: const Icon(Icons.navigation),
                        label: const Text('Route starten'),
                      ),
                    ],
                  ),
                ),
              ),
            ),

          if (_selected != null && _showTaxiStands)
            Positioned(
              left: 12,
              right: 12,
              bottom: 12,
              child: Card(
                elevation: 8,
                child: Padding(
                  padding: const EdgeInsets.all(14),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    crossAxisAlignment:
                        CrossAxisAlignment.stretch,
                    children: [
                      Row(
                        children: [
                          Expanded(
                            child: Text(
                              _selected!.name,
                              style: const TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                          Chip(
                            label: Text(
                              _selected!.score == null
                                  ? 'Nachfrage unbekannt'
                                  : 'Beispielwert ${_selected!.score}/100',
                            ),
                          ),
                        ],
                      ),

                      Text(
                        _selected!.note,
                        textDirection: TextDirection.ltr,
                      ),

                      const SizedBox(height: 10),

                      Row(
                        children: [
                          Expanded(
                            child: FilledButton.icon(
                              onPressed: () =>
                                  _navigate(_selected!),
                              icon: const Icon(
                                Icons.navigation,
                              ),
                              label: const Text(
                                'Route starten',
                              ),
                            ),
                          ),

                          
                          ],
                      ),

                      if (demoSpots.isNotEmpty) ...[
                        const SizedBox(height: 6),
                        Text(
                          'Höchster Beispielwert: '
                          '${demoSpots.first.name} '
                          '(${demoSpots.first.score})',
                          textDirection: TextDirection.ltr,
                          style: const TextStyle(
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ],
                    ],
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }
}
// Four separate L-shaped corners, keeping the place icon visible.
class _DemandCornersPainter extends CustomPainter {
  final double strokeWidth;
  final double cornerLength;

  const _DemandCornersPainter({
    required this.strokeWidth,
    required this.cornerLength,
  });

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = Colors.black
      ..style = PaintingStyle.stroke
      ..strokeWidth = strokeWidth
      ..strokeCap = StrokeCap.round
      ..strokeJoin = StrokeJoin.round;
    final inset = strokeWidth / 2 + 2;
    final left = inset;
    final top = inset;
    final right = size.width - inset;
    final bottom = size.height - inset;
    final path = ui.Path()
      ..moveTo(left, top + cornerLength)
      ..lineTo(left, top)
      ..lineTo(left + cornerLength, top)
      ..moveTo(right - cornerLength, top)
      ..lineTo(right, top)
      ..lineTo(right, top + cornerLength)
      ..moveTo(left, bottom - cornerLength)
      ..lineTo(left, bottom)
      ..lineTo(left + cornerLength, bottom)
      ..moveTo(right - cornerLength, bottom)
      ..lineTo(right, bottom)
      ..lineTo(right, bottom - cornerLength);
    canvas.drawPath(path, paint);
  }

  @override
  bool shouldRepaint(covariant _DemandCornersPainter oldDelegate) =>
      strokeWidth != oldDelegate.strokeWidth ||
      cornerLength != oldDelegate.cornerLength;
}

